"""Import official Strengthened SHS (SSHS) curriculum guides into LAMDAG DB.

Sources (shs_parsed.json) are parsed records from the official DepEd SSHS
Budget-of-Work / Curriculum Guide PDFs:
  - Grade 11: 6 core subjects, 43 academic electives, 44 tech-pro electives
  - Grade 12: 44 academic electives (New G12 CGs + main-cluster G12 courses),
              48 tech-pro electives

Terms come from the PDF structure (Q1->T1, Q2->T2, Q3+Q4->T3; term-based BOWs
map directly). Weeks are auto-distributed 1-10 per term and codes are
auto-generated by assign_weeks_codes.py (weeks already present in the source
BOW3 tech-pro files are preserved).

Idempotent: subjects with code prefix 'SSHS-' are deleted first.

Run:  python database/import_shs.py [--db PATH] [--commit] [--parsed PATH]
"""

import argparse
import json
import os
import re
import shutil
import sqlite3
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

_DEF_DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), "matatag_cg.db")
_DEF_PARSED = os.path.join(os.path.dirname(os.path.abspath(__file__)), "shs_parsed.json")

# ---------------------------------------------------------------------------
# Curated subject table.
# Each entry: (kind, grade, name, [source files, best first])
# kind: CORE | ACAD | TECH   grade: "Grade 11" | "Grade 12"
# ---------------------------------------------------------------------------

CORE_G11 = [
    ("CORE", "Grade 11", "Effective Communication",
     ["Effective-Communication-2.pdf", "Effective-Communication-1.pdf"]),
    ("CORE", "Grade 11", "General Mathematics",
     ["General-Mathematics-2.pdf", "GENERAL-MATHEMATICS-1.pdf"]),
    ("CORE", "Grade 11", "General Science",
     ["General-Science-2.pdf", "GENERAL-SCIENCE-1.pdf"]),
    ("CORE", "Grade 11", "Life and Career Skills",
     ["Life-and-Career-Skills-2.pdf", "LIFE-AND-CAREER-SKILLS-1.pdf"]),
    ("CORE", "Grade 11", "Mabisang Komunikasyon sa Wikang Filipino",
     ["Mabisang-Komunikasyon-2.pdf", "MABISANG-KOMUNIKASYON-1.pdf"]),
    ("CORE", "Grade 11", "Pag-aaral ng Kasaysayan at Lipunang Pilipino",
     ["Pag-aaral-ng-Kasaysayan-at-Lipunang-Pilipino-2.pdf",
      "PAG-AARAL-NG-KASAYSAYAN-AT-LIPUNANG-PILIPINO-1.pdf"]),
]

ACAD_G11 = [
    # HUMSS
    ("ACAD", "Grade 11", "Contemporary Literature 1",
     ["Contemporary-Literature-1-2.pdf", "Contemporary-Literature-1-1.pdf"]),
    ("ACAD", "Grade 11", "Contemporary Literature 2",
     ["Contemporary-Literature-2-2.pdf", "Contemporary-Literature-2-1.pdf"]),
    ("ACAD", "Grade 11", "Creative Composition 1",
     ["Creative-Composition-1-1.pdf", "Creative-Composition-1-2.pdf"]),
    ("ACAD", "Grade 11", "Creative Composition 2",
     ["Creative-Composition-2-1.pdf", "Creative-Composition-2-2.pdf"]),
    ("ACAD", "Grade 11", "Introduction to Philosophy",
     ["Introduction-to-Philosophy-1.pdf"]),
    ("ACAD", "Grade 11", "Malikhaing Pagsulat",
     ["Malikhaing-Pagsulat-Updated-as-of-060526.pdf", "Malikhaing-Pagsulat-1.pdf"]),
    ("ACAD", "Grade 11", "Filipino 1 (Wika at Komunikasyon sa Akademikong Filipino)",
     ["Filipino-1-Wika-at-Komunikasyon-sa-Akademikong-Filipino-Updated-as-of-060526.pdf",
      "Filipino-1-Wika-at-Komunikasyon-sa-Akademikong-Filipino-1.pdf"]),
    # Arts and Design
    ("ACAD", "Grade 11", "Creative Industries - Applied and Traditional Arts",
     ["Creative-Industries-Applied-and-Traditional-Arts.pdf"]),
    ("ACAD", "Grade 11", "Creative Industries - Dance",
     ["Creative-Industries-Dance.pdf"]),
    ("ACAD", "Grade 11", "Creative Industries - Literary Arts",
     ["Creative-Industries-Literary-Arts.pdf"]),
    ("ACAD", "Grade 11", "Creative Industries - Media Arts",
     ["Creative-Industries-Media-Arts.pdf"]),
    ("ACAD", "Grade 11", "Creative Industries - Music",
     ["Creative-Industries-Music.pdf"]),
    ("ACAD", "Grade 11", "Creative Industries - Theater Arts",
     ["Creative-Industries-Theater-Arts.pdf"]),
    ("ACAD", "Grade 11", "Creative Industries - Visual Arts",
     ["Creative-Industries-Visual-Arts.pdf"]),
    ("ACAD", "Grade 11", "Filipino Identity Through the Arts",
     ["Filipino-Identity-Through-the-Arts-Updated-as-of-060526.pdf",
      "Filipino-Identity-Through-the-Arts-1.pdf"]),
    ("ACAD", "Grade 11", "Leadership and Management in the Arts",
     ["Leadership-and-Management-in-the-Arts-Updated-as-of-060526.pdf",
      "Leadership-and-Mangement-in-the-Arts-1.pdf"]),
    ("ACAD", "Grade 11", "Art Criticism and Creative Markets",
     ["Art-Criticism-and-Creative-Markets.pdf"]),
    ("ACAD", "Grade 11", "Performance Criticism and Creative Markets",
     ["Performance-Criticism-and-Creative-Markets.pdf"]),
    # ABM
    ("ACAD", "Grade 11", "Business 1 (Basic Accounting)",
     ["Business-1-Basic-Accounting-1.pdf", "Business-1-Basic-Accounting-2.pdf"]),
    ("ACAD", "Grade 11", "Business 2 (Business Finance and Income Taxation)",
     ["Business-2-Business-Finance-and-Income-Taxation-2.pdf",
      "Business-2-Business-Finance-and-Income-Taxation-1.pdf"]),
    ("ACAD", "Grade 11", "Introduction to Organization and Management",
     ["Introduction-to-Organization-and-Management-2.pdf",
      "Introduction-to-Organization-and-Management-1.pdf"]),
    # STEM
    ("ACAD", "Grade 11", "Biology 1",
     ["Biology-1-1.pdf", "Biology-1-2.pdf"]),
    ("ACAD", "Grade 11", "Biology 2",
     ["Biology-2-1.pdf", "Biology-2-2.pdf"]),
    ("ACAD", "Grade 11", "Chemistry 1",
     ["Chemistry-1-Updated-as-of-060526.pdf", "Chemistry-1.pdf"]),
    ("ACAD", "Grade 11", "Chemistry 2",
     ["Chemistry-2-Updated-as-of-073026.pdf", "Chemistry-2-2.pdf"]),
    ("ACAD", "Grade 11", "Physics 1",
     ["Physics-1-1.pdf", "Physics-1-2.pdf"]),
    ("ACAD", "Grade 11", "Physics 2",
     ["Physics-2-1.pdf", "Physics-2-2.pdf"]),
    ("ACAD", "Grade 11", "Earth and Space Science 1",
     ["Earth-and-Space-Science-1-1.pdf", "Earth-and-Space-Science-1-2.pdf"]),
    ("ACAD", "Grade 11", "Earth and Space Science 2",
     ["Earth-and-Space-Science-2-1.pdf", "Earth-and-Space-Science-2-2.pdf"]),
    ("ACAD", "Grade 11", "Finite Mathematics 1",
     ["Finite-Mathematics-1-1.pdf", "Finite-Mathematics-1-2.pdf"]),
    ("ACAD", "Grade 11", "Finite Mathematics 2",
     ["Finite-Mathematics-2-1.pdf", "Finite-Mathematics-2-2.pdf"]),
    # Sports, Health, and Wellness
    ("ACAD", "Grade 11", "Human Movement 1 (Basic Anatomy in Sports and Exercise)",
     ["Human-Movement-1-Basic-Anatomy-in-Sports-and-Exercise-Updated-as-of-060526.pdf",
      "Human-Movement-1-Basic-Anatomy-in-Sports-and-Exercise-1.pdf"]),
    ("ACAD", "Grade 11", "Human Movement 2 (Motor Skills Development)",
     ["Human-Movement-2-Motor-Skills-Development-Updated-as-of-060526.pdf",
      "Human-Movement-2-Motor-Skills-Development-1.pdf"]),
    ("ACAD", "Grade 11", "Physical Education 1 (Fitness and Recreation)",
     ["Physical-Education-1-Fitness-and-Recreation-1.pdf",
      "Physical-Education-1-Fitness-and-Recreation-2.pdf"]),
    ("ACAD", "Grade 11", "Physical Education 2 (Sports and Dance)",
     ["Physical-Education-2-Sports-and-Dance-1.pdf",
      "Physical-Education-2-Sports-and-Dance-2.pdf"]),
    ("ACAD", "Grade 11", "Sports Coaching 1",
     ["Sports-Coaching-1.pdf"]),
    ("ACAD", "Grade 11", "Sports Officiating 1",
     ["Sports-Officiating-1.pdf"]),
]

ACAD_G12 = [
    # STEM
    ("ACAD", "Grade 12", "Biology 3",
     ["Biology-3-1.pdf", "BIOLOGY-3.pdf"]),
    ("ACAD", "Grade 12", "Biology 4",
     ["Biology-4-1.pdf", "BIOLOGY-4.pdf"]),
    ("ACAD", "Grade 12", "Chemistry 3",
     ["Chemistry-3-1.pdf", "CHEMISTRY-3.pdf"]),
    ("ACAD", "Grade 12", "Chemistry 4",
     ["Chemistry-4-1.pdf", "CHEMISTRY-4.pdf"]),
    ("ACAD", "Grade 12", "Physics 3",
     ["Physics-3-1.pdf", "PHYSICS-3.pdf"]),
    ("ACAD", "Grade 12", "Physics 4",
     ["Physics-4-1.pdf", "PHYSICS-4.pdf"]),
    ("ACAD", "Grade 12", "Earth and Space Science 3",
     ["Earth-and-Space-Science-3-1.pdf", "EARTH-AND-SPACE-SCIENCE-3.pdf"]),
    ("ACAD", "Grade 12", "Earth and Space Science 4",
     ["Earth-and-Space-Science-4-1.pdf", "EARTH-AND-SPACE-SCIENCE-4.pdf"]),
    ("ACAD", "Grade 12", "Advanced Mathematics",
     ["Advanced-Mathematics-Updated-as-of-05.29.26.pdf",
      "1-Updated-as-of-05.29.26_Advanced-Mathematics.pdf"]),
    ("ACAD", "Grade 12", "Basic Calculus",
     ["Basic-Calculus-Updated-as-of-05.29.26.pdf",
      "2-Updated-as-of-05.29.26_Basic-Calculus.pdf"]),
    ("ACAD", "Grade 12", "Pre-Calculus",
     ["Pre-Calculus-1.pdf", "Pre-Calculus.pdf"]),
    ("ACAD", "Grade 12", "Database Management",
     ["Database-Management-Updated-as-of-05.29.26-.pdf",
      "5-Updated-as-of-05.29.26_Database-Management.pdf"]),
    ("ACAD", "Grade 12", "Fundamentals of Data Analytics",
     ["Fundamentals-of-Data-Analytics-Updated-as-of-05.29.26.pdf",
      "6-Updated-as-of-05.29.26_Fundamentals-of-Data-Analytics.pdf"]),
    ("ACAD", "Grade 12", "Empowerment Technologies",
     ["Empowerment-Technologies-Updated-as-of-05.29.26-.pdf",
      "7-Updated-as-of-05.29.26_Empowerment-Technologies.pdf"]),
    ("ACAD", "Grade 12", "Conceptual Physics and Chemistry in Daily Life",
     ["Conceptual-Physics-and-Chemistry-in-Daily-Life-Updated-as-of-05.29.26.pdf",
      "3-Updated-as-of-05.29.26_Conceptual-Physics-and-Chemistry-in-Daily-Life.pdf"]),
    ("ACAD", "Grade 12", "Conceptual Biology and Earth and Space Science",
     ["Conceptual-Biology-and-Earth-and-Space-Science-Updated-as-of-05.29.26.pdf",
      "4-Updated-as-of-05.29.26_Conceptual-Biology-and-Earth-and-Space-Science.pdf"]),
    # HUMSS
    ("ACAD", "Grade 12", "Introduction to the Philosophy of the Human Person",
     ["Introduction-to-the-Philosophy-of-Human-Person.pdf"]),
    ("ACAD", "Grade 12", "Philippine Governance (Philippine Politics and Governance)",
     ["Philippine-Governance-Philippine-Politics-and-Governance-Updated-as-of-060526.pdf",
      "Philippine-Governance-Philippine-Politics-and-Governance-1.pdf"]),
    ("ACAD", "Grade 12", "Social Sciences (Theory and Practice)",
     ["Social-Sciences-Theory-and-Practice-Updated-as-of-060526.pdf",
      "Social-Sciences-Theory-and-Practice-1.pdf"]),
    ("ACAD", "Grade 12", "Citizenship and Civic Engagement",
     ["Citizenship-and-Civic-Engagement-Updated-as-of-060526.pdf",
      "Citizenship-and-Civic-Engagement-1.pdf"]),
    ("ACAD", "Grade 12", "Filipino 2 (Filipino sa Isports)",
     ["Filipino-2-Filipino-sa-Isports-1.pdf",
      "Filipino-2-Filipino-sa-Isports-Updated-as-of-060526.pdf"]),
    ("ACAD", "Grade 12", "Filipino 2 (Filipino para sa Larang Teknikal Propesyonal)",
     ["Filipino-2-Filipino-sa-Larang-Teknikal-Propesyonal-Updated-as-of-060526.pdf",
      "Filipino-2-Filipino-para-sa-Larang-Teknikal-Propesyonal-1.pdf"]),
    ("ACAD", "Grade 12", "Filipino 2 (Filipino sa Sining at Disenyo)",
     ["Filipino-2-Filipino-sa-Sining-at-Disenyo-Updated-as-of-060526.pdf",
      "Filipino-2-Filipino-sa-Sining-at-Disenyo-1.pdf"]),
    # ABM
    ("ACAD", "Grade 12", "Business 3 (Business Economics)",
     ["Business-3-Business-Economics-2.pdf", "Business-3-Business-Economics-1.pdf"]),
    ("ACAD", "Grade 12", "Contemporary Marketing",
     ["Contemporary-Marketing.pdf", "Contemprary-Marketing-1.pdf"]),
    ("ACAD", "Grade 12", "Entrepreneurship",
     ["Entrepreneurship-1.pdf", "Entrepreneurship-2.pdf"]),
    # Sports, Health, and Wellness
    ("ACAD", "Grade 12", "Sports Coaching 2",
     ["Sports-Coaching-2.pdf"]),
    ("ACAD", "Grade 12", "Sports Officiating 2",
     ["Sports-Officiating-2.pdf"]),
    ("ACAD", "Grade 12", "Sports Activity Management",
     ["Sports-Activity-Management-Updated-as-of-060526.pdf",
      "Sports-Activity-Management-1.pdf"]),
    ("ACAD", "Grade 12", "First Aid",
     ["First-Aid-1.pdf", "First-Aid.pdf"]),
    ("ACAD", "Grade 12", "Fundamentals of Basic Life Support",
     ["Fundamentals-of-Basic-Life-Support-1.pdf", "Fundamentals-of-Basic-Life-Support.pdf"]),
    ("ACAD", "Grade 12", "Exercise and Sports Programming",
     ["Exercise-and-Sports-Programming-1.pdf", "Exercise-and-Sports-Programming.pdf"]),
    # Field Experience / Arts Apprenticeship
    ("ACAD", "Grade 12", "Creative Production and Presentation",
     ["Creative-Production-and-Presentation-1.pdf", "CREATIVE-PRODUCTION-AND-PRESENTATION.pdf"]),
    ("ACAD", "Grade 12", "Design and Innovation",
     ["Design-and-Innovation.pdf", "2-Design-and-Innovation.pdf"]),
    ("ACAD", "Grade 12", "In-Campus Field Exposure for Sports",
     ["In-Campus-Field-Exposure-for-Sports-.pdf",
      "1-Updated-as-of-05.29.26_In-Campus-Field-Exposure-for-Sports.pdf"]),
    ("ACAD", "Grade 12", "Research 1",
     ["Research-1-1.pdf", "Research-1.pdf"]),
    ("ACAD", "Grade 12", "Research 2",
     ["Research-2-1.pdf", "Research-2.pdf"]),
    ("ACAD", "Grade 12", "Arts Apprenticeship - Dance",
     ["ARTS-APPRENTICESHIP-DANCE.pdf", "Arts-Apprenticeship-_-Dance.pdf"]),
    ("ACAD", "Grade 12", "Arts Apprenticeship - Literary Arts",
     ["ARTS-APPRENTICESHIP-LITERARY-ARTS.pdf", "Arts-Apprenticeship-Literary-Arts-1.pdf"]),
    ("ACAD", "Grade 12", "Arts Apprenticeship - Media Arts",
     ["ARTS-APPRENTICESHIP-MEDIA-ARTS.pdf", "Arts-Apprenticeship-Media-Arts-1.pdf"]),
    ("ACAD", "Grade 12", "Arts Apprenticeship - Music",
     ["ARTS-APPRENTICESHIP-MUSIC.pdf", "Arts-Apprenticeship-_-Music-.pdf"]),
    ("ACAD", "Grade 12", "Arts Apprenticeship - Theater Arts",
     ["ARTS-APPRENTICESHIP-THEATER-ARTS.pdf", "Arts-Apprenticeship-_-Theater-Arts-.pdf"]),
    ("ACAD", "Grade 12", "Arts Apprenticeship - Traditional Cultural Expressions",
     ["ARTS-APPRENTICESHIP-TRADITIONAL-CULTURAL-EXPRESSION.pdf",
      "Arts-Apprenticeship-_-Traditional-Cultural-Expressions-.pdf"]),
    ("ACAD", "Grade 12", "Arts Apprenticeship - Visual Arts",
     ["ARTS-APPRENTICESHIP-VISUAL-ARTS.pdf", "Arts-Apprenticeship-_-Visual-Arts.pdf"]),
]

# (name, g11_file, g12_file)  -- shared two-grade tech-pro electives
TECH_BOTH = [
    ("Aesthetic Services (Beauty Care)",
     "G11-Aesthetic-Services-Beauty-Care-1.pdf", "G12-Aesthetic-Services-Beauty-Care-1.pdf"),
    ("Agricultural Crops Production",
     "G11-Agricultural-Crops-Production-1.pdf", "G12-Agricultural-Crops-Production-1.pdf"),
    ("Agro-Entrepreneurship",
     "G11-Agro-Entrepreneurship-1.pdf", "G12-Agro-Entrepreneurship-1.pdf"),
    ("Animation",
     "G11-Animation-.pdf", "G12-Animation-1.pdf"),
    ("Aquaculture",
     "G11-Aquaculture-1.pdf", "G12-Aquaculture-1.pdf"),
    ("Bakery Operations",
     "G11-Bakery-Operations.pdf", "G12-Bakery-Operations-1.pdf"),
    ("Broadband Installation",
     "G11-Broadband-Installation.pdf", "G12-Broadband-Installation.pdf"),
    ("Caregiving (Adult Care)",
     "G11-Caregiving-Adult-Care-1.pdf", "G12-Caregiving-Adult-Care-1.pdf"),
    ("Caregiving (Child Care)",
     "G11-Caregiving-Child-Care-1.pdf", "G12-Caregiving-Child-Care-1.pdf"),
    ("Carpentry",
     "G11-Carpentry-1.pdf", "G12-Carpentry-1.pdf"),
    ("Computer Programming (.NET Technology)",
     "G11-Computer-Programming-.Net-Technology.pdf", "G12-Computer-Programming.Net-Technology.pdf"),
    ("Computer Programming (Java)",
     "G11-Computer-Programming-Java.pdf", "G12-Computer-Programming-Java-1.pdf"),
    ("Computer Programming (Oracle Database)",
     "G11-Computer-Programming-Oracle-Database.pdf", "G12-Computer-Programming-Oracle-Database-1.pdf"),
    ("Computer Systems Servicing",
     "G11-Computer-Systems-Servicing.pdf", "G12-Computer-Systems-Servicing-1.pdf"),
    ("Construction Operation",
     "G11-Construction-Operation-1.pdf", "G12-Construction-Operation-1.pdf"),
    ("Contact Center Services",
     "G11-Contact-Center-Services.pdf", "G12-Contact-Center-Services-1.pdf"),
    ("Domestic Refrigeration and Air Conditioning Servicing",
     "G11-Domestic-Refrigeration-and-Air-Conditioning-Servicing.pdf",
     "G12-Domestic-Refrigeration-And-Air-Conditioning-Servicing-1.pdf"),
    ("Driving and Automotive Servicing",
     "G11-Driving-and-Automotive-Servicing-1.pdf", "G12-Driving-And-Automotive-Servicing-2.pdf"),
    ("Electrical Installation and Maintenance",
     "G11-Electrical-Installation-and-Maintenance.pdf", "G12-Electrical-Installation-And-Maintenance-1.pdf"),
    ("Electronic Products Assembly and Servicing",
     "G11-Electronic-Products-Assembly-and-Servicing-.pdf", "G12-Electronic-Products-Assembly-And-Servicing-1.pdf"),
    ("Event Management Services",
     "G11-Event-Management-Services.pdf", "G12-Event-Management-Services.pdf"),
    ("Fish Capture Operation",
     "G11-Fish-Capture-Operation-1.pdf", "G12-Fish-Capture-Operation-1.pdf"),
    ("Food and Beverage Operations",
     "G11-Food-and-Beverage-Operation.pdf", "G12-Food-and-Beverage-Operations.pdf"),
    ("Food Processing",
     "G11-Food-Processing-1.pdf", "G12-Food-Processing-1.pdf"),
    ("Garments Artisanry",
     "G11-Garments-Artisanry.pdf", "G12-Garments-Artisanry.pdf"),
    ("Hairdressing Services",
     "G11-Hairdressing-Services-1.pdf", "G12-Hairdressing-Services-1.pdf"),
    ("Handicrafts (Weaving)",
     "G11-Handicrafts_-Weaving.pdf", "G12-Handicrafts_-Weaving.pdf"),
    ("Hospitality Operations - Front Office Services",
     "G11-Hotel-Operations-Front-Office-Services.pdf", "G12-Hospitality-Operations-Front-Office-Services.pdf"),
    ("Hospitality Operations - Housekeeping Services",
     "G11-Hotel-Operations-Housekeeping-Services.pdf", "G12-Hospitality-Operations-Housekeeping-Services.pdf"),
    ("Illustration",
     "G11-Illustration-.pdf", "G12-Illustration-.pdf"),
    ("Kitchen Operations",
     "G11-Kitchen-Operations.pdf", "G12-Kitchen-Operations-1.pdf"),
    ("Manual Metal Arc Welding",
     "G11-Manual-Metal-Arc-Welding-1.pdf", "G12-Manual-Metal-Arc-Welding-1.pdf"),
    ("Maritime Engineering at the Support Level",
     "G11-Maritime-Engineering-at-the-Support-Level.docx.pdf", "G12-Maritime-Engineering-at-the-Support-Level-.pdf"),
    ("Maritime Transportation at the Support Level",
     "G11-Maritime-Transportation-at-the-Support-Level.pdf", "G12-Maritime-Transportation-at-the-Support-Level.docx.pdf"),
    ("Motorcycle and Small Engine Servicing",
     "G11-Motorcycle-and-Small-Engine-Servicing-1-1.pdf", "G12-Motorcycle-And-Small-Engine-Servicing.docx-1.pdf"),
    ("Organic Agriculture Production",
     "G11-Organic-Agriculture-Production-1-1.pdf", "G12-Organic-Agriculture-Production-1.pdf"),
    ("Photovoltaic Systems Installation",
     "G11-Photovoltaic-Systems-Installation.pdf", "G12-Photovoltaic-Systems-Installation-1.pdf"),
    ("Poultry Production (Chicken)",
     "G11-Poultry-Production-Chicken-1.pdf", "G12-Poultry-Production-Chicken-1.pdf"),
    ("Ruminants Production",
     "G11-Ruminants-Production-1.pdf", "G12-Ruminants-Production-1.pdf"),
    ("Ships Catering Services",
     "G11-Ships-Catering-Services.pdf", "G12-Ships-Catering-Services-1.pdf"),
    ("Swine Production",
     "G11-Swine-Production-1.pdf", "G12-Swine-Production-1.pdf"),
    ("Technical Drafting",
     "G11-Technical-Drafting-1.pdf", "G12-Technical-Drafting-1.pdf"),
    ("Tourism Services",
     "G11-Tourism-Services.pdf", "G12-Tourism-Services-1.pdf"),
    ("Visual Graphic Design",
     "G11-Visual-Graphic-Design.pdf", "G12-Visual-Graphic-Design-1.pdf"),
]

# (name, g12_file)  -- Grade 12 only tech-pro electives
TECH_G12_ONLY = [
    ("Automotive Servicing (Electrical Repair)",
     "G12-Automotive-Servicing-Electrical-Repair-1-1.pdf"),
    ("Automotive Servicing (Engine and Chassis Repairs)",
     "G12-Automotive-Servicing-Engine-and-Chassis-Repairs-1.pdf"),
    ("Commercial Air Conditioning Installation and Servicing",
     "G12-Commercial-Air-Conditioning-Installation-And-Servicing.docx-1.pdf"),
    ("Mechatronics",
     "G12-Mechatronics.pdf"),
]


def build_subjects():
    subs = list(CORE_G11) + list(ACAD_G11) + list(ACAD_G12)
    for name, g11, g12 in TECH_BOTH:
        subs.append(("TECH", "Grade 11", name, [g11]))
        subs.append(("TECH", "Grade 12", name, [g12]))
    for name, g12 in TECH_G12_ONLY:
        subs.append(("TECH", "Grade 12", name, [g12]))
    return subs


def slugify(name):
    s = name.upper().replace("(SSHS)", "").replace("(", "").replace(")", "")
    s = re.sub(r"[^A-Z0-9]", "", s)
    return s


def grade_num(grade):
    m = re.fullmatch(r"Grade (\d+)", grade)
    return int(m.group(1)) if m else 99


_FOOTER = re.compile(
    r"(?:Page \d+ of \d+|Pahina \d+ ng \d+)"
    r"(?: (?:Last updated|Huling na-update noong) [A-Za-z]+ \d{1,2}, \d{4})?"
    r"(?: ?(?:Budget of Work|Budget ng Gawaing Pagkatuto) (?:Grade|Baitang) \d+ \| ?)?"
)


def clean(text):
    if not text:
        return ""
    t = _FOOTER.sub("", text)
    t = re.sub(r"[ \t]+", " ", t).strip()
    return t


def main():
    ap = argparse.ArgumentParser(description="Import official SSHS curriculum into LAMDAG DB")
    ap.add_argument("--db", default=None, help=f"target sqlite db path (default: {_DEF_DB})")
    ap.add_argument("--parsed", default=None, help=f"parsed json path (default: {_DEF_PARSED})")
    ap.add_argument("--commit", action="store_true")
    args = ap.parse_args()

    DB = args.db or _DEF_DB
    PARSED = args.parsed or _DEF_PARSED

    subs = build_subjects()
    print(f"subjects planned: {len(subs)}")

    with open(PARSED, encoding="utf-8") as f:
        recs = json.load(f)
    by_file = {}
    for r in recs:
        by_file.setdefault(r["file"], []).append(r)
    print(f"parsed records: {len(recs)} from {len(by_file)} files")

    # validate file references
    missing = set()
    for _, _, _, files in subs:
        for f in files:
            if f not in by_file:
                missing.add(f)
    if missing:
        print("MISSING SOURCE FILES:")
        for f in sorted(missing):
            print("   ", f)
        sys.exit(1)

    # backup db
    bak = DB + ".bak"
    shutil.copy2(DB, bak)
    print(f"backup -> {bak}")

    conn = sqlite3.connect(DB)
    conn.execute("PRAGMA foreign_keys = ON")
    cur = conn.cursor()

    # existing (grade, name) to detect collisions with legacy rows
    existing_names = {}
    for row in cur.execute("SELECT grade_level, name FROM subjects"):
        existing_names.setdefault(row[0], set()).add(row[1])

    # idempotency: drop previous SSHS import (same transaction, committed at end)
    cur.execute("DELETE FROM competencies WHERE subject_id IN "
                "(SELECT id FROM subjects WHERE code LIKE 'SSHS-%')")
    cur.execute("DELETE FROM subjects WHERE code LIKE 'SSHS-%'")
    print("will remove previous SSHS import (code LIKE 'SSHS-%')")

    # assign codes, detect same-grade same-name collisions
    used_codes = set()
    resolved = []
    for kind, grade, name, files in subs:
        final_name = name
        if grade in existing_names and name in existing_names[grade]:
            final_name = name + " (SSHS)"
        code = f"SSHS-{kind}-{slugify(final_name)}-G{grade_num(grade)}"
        if code in used_codes:
            code = code + f"-{len(used_codes)}"
        used_codes.add(code)
        resolved.append((kind, grade, final_name, files, code))

    # insert subjects
    for kind, grade, name, files, code in resolved:
        cur.execute(
            "INSERT OR IGNORE INTO subjects (code, name, grade_level, sort_order) VALUES (?, ?, ?, ?)",
            (code, name, grade, grade_num(grade)),
        )

    cur.execute("SELECT code, id FROM subjects WHERE code LIKE 'SSHS-%'")
    sid = {row[0]: row[1] for row in cur.fetchall()}

    # insert competencies (dedupe within term across source files)
    total = 0
    dupes = 0
    for kind, grade, name, files, code in resolved:
        best = {}
        for f in files:
            for r in by_file.get(f, []):
                desc = clean(r["description"])
                if not desc:
                    continue
                term = r["term"]
                key = (term, desc.casefold())
                if key not in best:
                    best[key] = r
                else:
                    dupes += 1
        # order per term follows first-seen source order -> stable seq
        per_term = {}
        for (term, _), r in best.items():
            per_term.setdefault(term, []).append(r)
        for term in sorted(per_term):
            seq = 0
            for r in per_term[term]:
                seq += 1
                week = r.get("week")
                ccode = f"{code}-T{term}-{seq:02d}"
                cur.execute(
                    """INSERT OR IGNORE INTO competencies
                       (subject_id, term, week, code, description, content_standard, performance_standard)
                       VALUES (?, ?, ?, ?, ?, ?, ?)""",
                    (sid[code], term, week, ccode, clean(r["description"]),
                     clean(r.get("content_standard")), clean(r.get("performance_standard"))),
                )
                total += 1
    print(f"competencies inserted: {total} (duplicate rows skipped: {dupes})")

    # report per subject / grade / term
    print("\n--- per subject / grade / term ---")
    for row in cur.execute(
        """SELECT s.grade_level, s.code, s.name, c.term, COUNT(*)
           FROM subjects s LEFT JOIN competencies c ON c.subject_id = s.id
           WHERE s.code LIKE 'SSHS-%'
           GROUP BY s.id, c.term
           ORDER BY s.grade_level, s.sort_order, s.name, c.term"""):
        print(f"  {row[0]:9s} {row[1]:34s} {row[2][:44]:44s} T{row[3]}: {row[4]}")

    print("\n--- DB totals ---")
    print("subjects:", cur.execute("SELECT COUNT(*) FROM subjects").fetchone()[0])
    print("competencies:", cur.execute("SELECT COUNT(*) FROM competencies").fetchone()[0])
    print("SSHS subjects:", cur.execute("SELECT COUNT(*) FROM subjects WHERE code LIKE 'SSHS-%'").fetchone()[0])
    print("SSHS competencies:", cur.execute(
        "SELECT COUNT(*) FROM competencies WHERE subject_id IN "
        "(SELECT id FROM subjects WHERE code LIKE 'SSHS-%')").fetchone()[0])

    if not args.commit:
        conn.rollback()
        print("\nDRY RUN (rolled back). Re-run with --commit to save.")
    else:
        conn.commit()
        print("\nCOMMITTED.")
    conn.close()


if __name__ == "__main__":
    main()
